### ISSUE TITLE
environment.yml? 

### ISSUE THREAD

**Issue by rsignell-usgs** [skybristol/experiments#2]
@skybristol is there an `environment.yml` file that would run all these notebooks?

**Comment by skybristol** [comment]
Gee! That'd be handy, huh? Maybe I should call this "messy_experiments." I'll get around that soonish... Thanks for the prompt.

**Comment by skybristol** [comment]
@rsignell-usgs - I threw an environment.yml in and cleaned up a few things. I also tweaked the latest notebook on the slido stuff from yesterday to help someone else use their own OpenAI key if you want to actually run it or tweak it yourself.
